# Remember, YAML does not understand the 'tab' key. You must use spaces instead. 
# Note that this plugin REQUIRES you have Vault. Download it here: http://dev.bukkit.org/server-mods/vault/

# If this is true, it will override any groups when someone ranks up. Only worry about this if a given person may have multiple ranks.
settings:
    override-groups: false
# Groups are ordered in the succession you want them to be.
# Group format:
# name:
#     price: 12.5
#     default: false [NOT REQUIRED]
#     broadcast: false [NOT REQUIRED]
#     pay: 100.0 [NOT REQUIRED]
# Pay is how much they are paid per hour if the pay plugin is installed.
# Note, there's four spaces on sub-values.
ranks:
    guest:
        price: 0
        default: true
        broadcast: false
    member: 15000
        pay: 100